name: naqelapp
description: A new Flutter application.
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  progress_dialog: ^1.1.0+1
  country_list_pick: ^1.0.0+4
  flutter_spinkit: "^4.1.2"
  simple_animations: ^1.3.3
  firebase_auth: ^0.16.1
  email_validator: '^1.0.0'
  image_picker: ^0.6.3+1
  location: ^3.0.0
  geolocator: ^5.3.1
  flutter_swiper: ^1.1.6
  badges: ^1.1.1
  flutter_cupertino_date_picker: ^1.0.26
  rating_bar: ^0.2.0
  flutter_polyline_points: ^0.1.0
  google_maps_flutter:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.0+8
  json_serializable: ^3.3.0
  cloud_firestore: ^0.13.6
  google_map_location_picker: ^3.3.2
  firebase_storage: ^3.0.3
  firebase_database: ^3.1.6
  flutter_cache_manager: ^1.1.3
  shared_preferences: ^0.5.6+1
  http: ^0.12.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/bgs/bg-gradient.png
    - assets/bgs/bg-signup.png
    - assets/fonts/AcuminProBold.otf
    - assets/fonts/AcuminProRegular.otf
    - assets/fonts/SfProTextRegular.ttf
    - assets/fonts/SfProTextSemibold.ttf
    - assets/gif/load.gif
    - assets/icons/facebook.png
    - assets/icons/google-plus.png
    - assets/icons/lock-grey.png
    - assets/icons/lock.png
    - assets/icons/logo.jpeg
    - assets/icons/logo.png
    - assets/icons/not-show.png
    - assets/icons/show-grey.png
    - assets/icons/show.png
    - assets/icons/twitter.png
    - assets/icons/user-grey.png
    - assets/icons/user.png
    - assets/imgs/centerLogo.png
    - assets/imgs/curve.png
    - assets/imgs/img.png
